### ISSUE TITLE
Using a pointless interface.

### ISSUE THREAD

**Issue by ObscureCode** [Lloydaaa/Googl-Library-PHP#1]
Using interfaces kinda implies the interface is generic and interfaces with other classes. Like, you'd have to have more than one class implementing it or else you're just trying to look like you understand OOP but don't.

![alt text](http://i.stack.imgur.com/y3IN7.png)

Nice pointless one class interface. Your class has one responsibility, keep **its** stuff **in it**.

**Comment by Lloydaaa** [comment]
This will be expanded further and more classes will be implemented, closed.

**Comment by ObscureCode** [comment]
Well, that still beats the point.. what other class will implement that interface? It's very specific to the functionality of the Googl class. It's not a generic interface at all and only serves one class, making it a pointless thing to implement.
